### ISSUE TITLE
求阿里云部署phoenix的方案

### ISSUE THREAD

**Issue by 603010999** [mydearxym/phoenix-doc-in-chinese#2]
看到过网上其他人写的用nginx部署的方案，但是需要打发布包去部署
请问有没有办法实现在linux云服务器上开发，然后自己的windows下可以访问这样

**Comment by mydearxym** [comment]
不是很明白你的意思呢  云上开发？ 你是想要在服务器上直接改代码？

[jetbrains](https://www.jetbrains.com/) 家的工具都有个本地编辑然后自动用 ftp 同步到服务器的功能不知道能否满足你的要求。

**Comment by 603010999** [comment]
我是自己有个练习用的VPS，想直接修改完代码，直接用浏览器就能看结果

**Comment by mydearxym** [comment]
sorry, 如果你是想保存就自动部署的话，这个不知道，也觉得没必要吧。。

**Comment by 603010999** [comment]
不是保存就自动部署哈，是想调试看结果方便点
现在用nginx配置下就可以访问到了
之前是因为访问的端口一直没开，就以为是phoenix的设置有问题
